version: '3.7'

services:
  app:
    container_name: demo-app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    container_name: Postgresql
    image: postgres:10-alpine
    env_file:
      - ./.env
    # environment:
    #   - POSTGRES_HOST=${DB_HOST}
    #   - POSTGRES_DB=${DB_NAME}
    #   - POSTGRES_USER=${DB_USER}
    #   - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: